language: cpp
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      sudo: true
      compiler: gcc

packages:
  - cmake-data
  - cmake
    
apt:
  packages:
     - xauth
     - libgtk-3-0

services:
  - xvfb
  
before_install:
#sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#sudo apt-get update
#sudo apt-get install -y libwxgtk3.0-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

#wxWidgets 3.1
  - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - sudo sudo apt-add-repository 'deb http://repos.codelite.org/wx3.1.1/ubuntu/ xenial universe'
  - sudo apt-get update
  - sudo apt-get install libwxbase3.1-0-unofficial3
  - sudo apt-get install libwxbase3.1unofficial3-dev
  - sudo apt-get install libwxgtk3.1-0-unofficial3
  - sudo apt-get install libwxgtk3.1unofficial3-dev
  - sudo apt-get install  wx3.1-headers
  - sudo apt-get install wx-common
  
#OpenGL
  - sudo apt-get install freeglut3-dev
  - sudo apt-get install libglew-dev
  - sudo apt-get install mesa-utils

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90 
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - g++ --version
  - make
  - ls -la
#  - xvfb-run --server-args="-screen 0, 1024x768x24"
  - ./PSP-UFU
  - exit
